apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-infra
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Cluster-wide infra for every workload cluster. Only app-repo Project trusted with cluster-scoped resources.
  sourceRepos:
  - https://github.com/aben011/lab-cluster-infra
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: kube-system
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: storage.k8s.io
    kind: StorageClass

