apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-httproute.yaml
  - local-path-retain-storageclass.yaml
  - longhorn-httproute.yaml
  - traefik-gateway-helmchartconfig.yaml
