apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesCRD:
        enabled: true
        allowExternalNameServices: true
      kubernetesIngress:
        enabled: false
      kubernetesGateway:
        enabled: true

    gateway:
      listeners:
        web:
          hostname: "*.ab3704.duckdns.org"
          protocol: HTTP
          namespacePolicy:
            from: All

        websecure:
          port: 8443
          hostname: "*.ab3704.duckdns.org"
          protocol: HTTPS
          namespacePolicy:
            from: All
          certificateRefs:
          - kind: Secret
            name: x.ab3704.duckdns.org-secret
          mode: Terminate
