apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-infra
  namespace: argocd
spec:
  project: platform

  source:
    repoURL: https://github.com/aben011/lab-platform
    targetRevision: main
    path: infra/base

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
