apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-plane
  namespace: argocd
spec:
  project: mgmt-plane
  source:
    repoURL: https://github.com/aben011/lab-mgmt-plane
    targetRevision: refs/heads/main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true

