apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: x.ab3704-k.duckdns.org-cert
  namespace: kube-system
spec:
  secretName: x.ab3704-k.duckdns.org-secret
  issuerRef:
    name: duckdns-letsencrypt-prod
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
  dnsNames:
    - "*.ab3704-k.duckdns.org"
